<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Machine;
use App\Models\MachineType;

class MachineSeeder extends Seeder
{
    public function run(): void
    {

        $machines= [
            // Tipo, Patente, internal_id, Marca, Modelo, Observaciones
            ['ASFALTADORA','RSVH-62','FN-20','VOGELE','S1600 Clasic',''],
            ['ASFALTADORA','S/PP FN-19','FN-19','BARBER GREENE','BG-240B',''],
            ['BARREDORA','FPDJ-87','BA-20','LAY-MOR','8HC',''],
            ['BARREDORA','JLKK-42','BA-19','BROSE BROOM','RCT 350',''],
            ['BARREDORA','PFTV-64','BA-26','SUPERIOR BROM','DT80CT',''],
            ['BATEA','JL-4068','CT-34','RANDON','SR BA AB 03 20',''],
            ['BATEA','JL-4069','CT-33','RANDON','SR BA AB 03 20',''],
            ['BATEA','JN-8876','CT-48','RANDON','SR BA AB 03 20',''],
            ['CAMA BAJA','JD-2788','CB-01','HIGHWAY','T/Challenger',''],
            ['CAMA BAJA','JJ-2045','CB-22','CHALLENGER','RG-50',''],
            ['CAMA BAJA','PWXR-71','CB-25','TREMAC','SR Cama Baja Cargo Fast 50',''],
            ['CAMION ALJIBE','CHDK-65','CA-09','VOLVO','VM 310',''],
            ['CAMION ALJIBE','DPSW-50','CA-57','MACK','GU 813',''],
            ['CAMION ALJIBE','DYZB-69','CT-44','FAW','F3237',''],
            ['CAMION ALJIBE','DYZB-70','CA-10','FAW ','F3237',''],
            ['CAMION ALJIBE','GX-4888','CA-03','KENWORTH','T-450',''],
            ['CAMION ALJIBE','SRYR-96','CA-58','FAW','F3842',''],
            ['CAMION ALJIBE','TGDP-37','CA-59','SINOTRUCK','Sitrak G7 Faena',''],
            ['CAMION ALJIBE','TTSV-33','CA-65','SINOTRUCK','Sitrak G7 Faena',''],
            ['CAMION ALJIBE','ZK-5005','CT-14','SCANIA','P124',''],
            ['CAMION ALJIBE','ZR-7219','CT-15','SCANIA','P124','EN DESAR.'],
            ['CAMION IMPRIMADOR','FGPS-32','CI-12','FREIGHTLINER','M2 106',''],
            ['CAMION IMPRIMADOR','NA-2219','CI-11','MERCEDES BENZ','L1619/52',''],
            ['CAMION IMPRIMADOR','VGXB-37','CI-30','MERCEDES BENZ','ATEGO 1729 KO 48 AT',''],
            ['CAMION LECHADA','TTPP-28','CT-64','JAC','Lander HFC 3262',''],
            ['CAMION LIVIANO','BGTK - 49','CL-197','CHEVROLET','NPR 75P',''],
            ['CAMION LIVIANO','BPDR - 24','CL-207','CHEVROLET','NPR 75P',''],
            ['CAMION LIVIANO','DPFT-34','CL-240','MITSUBISHI','CANTER 7,5',''],
            ['CAMION LIVIANO','JTGV-77','CL-264','HINO','XZU 8.5',''],
            ['CAMION LIVIANO','LRSY-96','CL-268','CHEVROLET','NPR 816',''],
            ['CAMION LIVIANO','PGSK-63','CL-270','JAC','HFC 5049 Sunray Cargo Triple',''],
            ['CAMION LIVIANO','PKHP-64','CL-276','CHEVROLET','NPR 816',''],
            ['CAMION LIVIANO','TPYT-16','CL-311','HINO','XZU 917',''],
            ['CAMION LIVIANO','WZ-5983','CL-194','CHEVROLET','NPR 75P',''],
            ['CAMION TOLVA','CGZL-37','CT-26','SCANIA','P380B6X4',''],
            ['CAMION TOLVA','CGZL-38','CT-27','SCANIA','P380B6X4',''],
            ['CAMION TOLVA','CGZL-40','CT-29','SCANIA','P380B6X4',''],
            ['CAMION TOLVA','DKDG-59','CT-39','SCANIA','P380B6X4',''],
            ['CAMION TOLVA','DXCG-25','CT-40','SCANIA','P400B',''],
            ['CAMION TOLVA','DXCG-26','CT-41','SCANIA','P400B',''],
            ['CAMION TOLVA','DYZB-68','CT-45','FAW','F3237',''],
            ['CAMION TOLVA','FHVS-78','CT-43','SCANIA','P400B',''],
            ['CAMION TOLVA','FJGY-97','CT-42','SCANIA','P400B',''],
            ['CAMION TOLVA','HWGS-26','CT-46','SCANIA','P400B',''],
            ['CAMION TOLVA','HWGS-63','CT-47','SCANIA','P400B',''],
            ['CAMION TOLVA','KKPX-57','CT-53','SCANIA','P400B',''],
            ['CAMION TOLVA','KKPX-58','CT-54','SCANIA','P400B',''],
            ['CAMION TOLVA','PRTZ-21','CT-55','MERCEDES BENZ','Arocs 4848',''],
            ['CAMION TOLVA','PRTZ-24','CT-56','MERCEDES BENZ','Arocs 4848',''],
            ['CAMION TOLVA','TSJH-71','CT-62','SCANIA','P450B 8X4',''],
            ['CAMION TOLVA','TSJH-72','CT-63','SCANIA','P450B 8X4',''],
            ['CAMION TOLVA','ZR-7220','CT-16','SCANIA','P124','EN DESAR.'],
            ['CARGADOR FRONTAL','BRCW-93','CF-68','KOMATSU','WA320-6',''],
            ['CARGADOR FRONTAL','BZFJ-53','CF-69','KOMATSU','WA320-6','F/SERV.'],
            ['CARGADOR FRONTAL','CGJV-72','CF-71','KOMATSU','WA320-6',''],
            ['CARGADOR FRONTAL','FCDG-98','CF-73','CATERPILLAR','938 H',''],
            ['CARGADOR FRONTAL','GXTW-75','CF-74','CATERPILLAR','938 K',''],
            ['CARGADOR FRONTAL','JFWZ-96','CF-75','CATERPILLAR','962H',''],
            ['CARGADOR FRONTAL','TDZF-87','CF-78','CATERPILLAR','950 GC',''],
            ['CARGADOR FRONTAL','WG-2172','CF-65','CATERPILLAR','924 GZ',''],
            ['CARRO TOLVA','JF-6798','RT-35','CABURGA','RTC-12',''],
            ['CARRO TOLVA','JK-4686','RT-23','TREMAC','RTV-2-R',''],
            ['CARRO TOLVA','JK-4687','RT-24','TREMAC','RTV-2-R',''],
            ['CARRO TOLVA','JL-3518','RT-36','CABURGA','RTC12',''],
            ['CARRO TOLVA','JL-5759','RT-37','CABURGA','RTC12',''],
            ['CARRO TOLVA','JL-5760','RT-38','CABURGA','RTC12',''],
            ['CARRO TOLVA','JP-2771','RT-51','CABURGA','RTC 10',''],
            ['CARRO TOLVA','JP-2772','RT-52','CABURGA','RTC 10',''],
            ['CARRO TRANSPORTE','PXFF-69','CR-60','MAPAR','Transporte Maquinaria',''],
            ['CARRO TRANSPORTE','PXFF-71','CR-61','MAPAR','Transporte Maquinaria',''],
            ['CONO VSI','S/P TI-11','TI-11','ORE SIZER','OM 50',''],
            ['EXCAVADORA','CGJV-77','EX-29','KOMATSU','PC-200-8',''],
            ['EXCAVADORA','CLTX-46','EX-30','CATERPILLAR','320DL',''],
            ['EXCAVADORA','GXTW-76','EX-31','CATERPILLAR','320DL',''],
            ['EXCAVADORA','GZLW-54','EX -32','CATERPILLAR','320D',''],
            ['EXCAVADORA','PFXD-55','EX -34','KOMATSU','PC2010LC',''],
            ['EXCAVADORA','PFXD-91','EX -33','KOMATSU','PC210LC',''],
            ['EXCAVADORA','PSFX-71','EX -35','JCB','JS-305',''],
            ['EXCAVADORA','ZB-7056','EX-27','KOMATSU','PC-200-7',''],
            ['EXCAVADORA','ZW-4582','EX-28','KOMATSU','PC-200-8',''],
            ['GENERADOR  > 400 kva','S/PP GN-55','GN-55','LUREYE','CG410 kva','F/SERV.'],
            ['GENERADOR  > 400 kva','S/PP GN-61','GN-61','LUREYE','V440',''],
            ['GENERADOR  > 400 kva','S/PP GN-63','GN-63','LUREYE','GE V440',''],
            ['GRAVILLADORA','DWTC-32','GV-13','ETNYRE','K5519',''],
            ['GRAVILLADORA','FN-4104','GV-12','ETNYRE','ED. Etnyre',''],
            ['GRAVILLADORA','SGSR-72','GV-14','ETNYRE','K5848',''],
            ['MOTONIVELADORA','BFWV-48','MT-06','JHON DEERE','770D',''],
            ['MOTONIVELADORA','BRYS-80','MT-07','CATERPILLAR','140H',''],
            ['MOTONIVELADORA','CGRG-58','MT-10','JHON DEERE','772D',''],
            ['MOTONIVELADORA','DWCL-13','MT-11','CATERPILLAR','140K',''],
            ['MOTONIVELADORA','GXTW-74','MT-12','CATERPILLAR','140M',''],
            ['MOTONIVELADORA','JHJC-49','MT-13','CATERPILLAR','160K',''],
            ['MOTONIVELADORA','KVZR-35','MT-14','JHON DEERE','770G',''],
            ['MOTONIVELADORA','RPCH-59','MT-15','JHON DEERE','770G',''],
            ['MOTONIVELADORA','TKKC-81','MT-16','CATERPILLAR','140',''],
            ['MOTONIVELADORA','UY-3558','MT-08','VOLVO','G730ASVI',''],
            ['MOTONIVELADORA','UZ-1659','MT-09','VOLVO','G730',''],
            ['PLANTA ASFALTO','S/PP PA-17','PA-17','BARBER GREENE','CB-60',''],
            ['PLANTA AUTONOMA','S/P PL-09','PL-09','RUBBLER MASTER','RM 100 GO',''],
            ['PLANTA ÁRIDOS','S/P PL-01','PL-01','MARCA','0',''],
            ['PLANTA ÁRIDOS','S/P PL-04','PL-04','MARCA','0',''],
            ['PLANTA ÁRIDOS','S/P PL-08','PL-08','MARCA','0',''],
            ['RAMPLA ALTA','JB-6100','CR-25','GOREN','30 TON',''],
            ['RAMPLA ALTA','JG-3024','CR-30','TREMAC','20000',''],
            ['RAMPLA CERRADA','JD-2808','CR-06','MONTENEGRO','30 Ton.',''],
            ['RAMPLA CONTROL','S/P CM-08','CM-08','MARCA','0',''],
            ['RETROEXCAVADORA','DHVC-58','RT-72','CATERPILLAR','416E',''],
            ['RETROEXCAVADORA','KGBS-79','RT-76','KOMATSU','WB97R',''],
            ['RETROEXCAVADORA','MX-4367','RT-67','KOMATSU','WB-146-5',''],
            ['RETROEXCAVADORA','SFRY-74','RT-77','KOMATSU','WB97R',''],
            ['RETROEXCAVADORA','TRKP-74','RT-79','CATERPILLAR','416F',''],
            ['RETROEXCAVADORA','XW-8146','RT-66','CATERPILLAR','416E',''],
            ['RODILLO ASFALTO','DCHJ-45','RA-23','STAVOSTROJ','VP 2400',''],
            ['RODILLO ASFALTO','GLZR-98','RA-24','INGERSOLL RAND','PT 240 R',''],
            ['RODILLO ASFALTO','KTRV-26','RA-25','HAMM','GRW280 12H',''],
            ['RODILLO ASFALTO','VJHX-41','RA-28','HAMM','HP280I 12',''],
            ['RODILLO COMPACTADOR','BFWV-47','RC-05','HAMM','3410','F/SERV.'],
            ['RODILLO COMPACTADOR','CGRG-57','RC-07','HAMM','3410',''],
            ['RODILLO COMPACTADOR','FHVK-44','RC-08','HAMM','3412',''],
            ['RODILLO COMPACTADOR','FPVT-98','RC-09','HAMM','HD-12VT',''],
            ['RODILLO COMPACTADOR','GZKZ-84','RC-10','HAMM','3410',''],
            ['RODILLO COMPACTADOR','LBXF-90','RC-11','VOLVO','SD110B',''],
            ['RODILLO COMPACTADOR','PTSP-17','RC-12','BOMAG','BW211 D40',''],
            ['RODILLO COMPACTADOR','TTHV-92','RC-13','CATERPILLAR','CS10 GC',''],
            ['RODILLO COMPACTADOR','UP-8569','RC-06','INGERSOLL RAND','SD100D  B',''],
            ['RODILLO COMPACTADOR','XK-2998','RC-01','BOMAG','BW 211 D-3',''],
            ['RODILLO D.TAMBOR','VKXY-34','RA-29','HAMM','HD 80IVO',''],
            ['RODILLO D.TAMBOR','ZP-3894','RC-04','HAMM','HD-75',''],
            ['SELLADORA','S/P XX-01','XX-01','MARCA','0',''],
            ['TRACTOCAMION','BHZJ - 74','TC-17','SCANIA','G420A6X4CG19',''],
            ['TRACTOCAMION','CTYY-48','TC-31','SCANIA','G340',''],
            ['TRACTOCAMION','DFGS-92','TC-32','SCANIA','G340',''],
            ['TRACTOCAMION','GDFS-82','TC-50','FAW','F-2642',''],
            ['TRACTOCAMION','VDLP-96','TC-66','SCANIA','500',''],
            ['TRACTOR AGRICOLA','PLKR-30','TT-17','LOVOL','Europard TD904K',''],
            ['GENERADOR < 399 kva','S/PP GN-51','GN-51','CUMMING','312 KVA',''],
            ['GENERADOR < 399 kva','S/PP GN-53','GN-53','LUREYE','250 Kva F/SERV',''],
            ['GENERADOR < 399 kva','S/PP GN-56','GN-56','JHON DEERE','275 KVA MODELO 6081H',''],
            ['GENERADOR < 399 kva','S/PP GN-59','GN-59','DEUTZ CELESTE','200 KVA',''],
            ['GENERADOR < 399 kva','S/PP GN-60','GN-60','CUMMING','C400D5 360 KVA','F/SERV.']
        ];

        foreach ($machines as $data) {
            $machineType = MachineType::where('name', $data[0])->first();
            if(!$machineType) {
                $machineType = MachineType::create(['name' => $data[0]]);
            }

            Machine::create([
                'machine_type_id' => $machineType->id,
                'plate' => $data[1],
                'internal_id' => $data[2],
                'brand' => $data[3],
                'model' => $data[4],
                'observations' => $data[5],
                'fuel_type' => 'Diésel',
                'fuel_capacity' => 400,
            ]);
        }
    }
}
